version: '3.8'

services:

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: vpn-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app_dev.conf:/etc/nginx/conf.d/app.conf
        links:
            - app


    #Python Service
    app:
        env_file: .env
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
            args:
                - PROJECT_URL=${PROJECT_DEV_URL}
                - TELEGRAM_BOT_API_TOKEN=${TELEGRAM_BOT_API_TOKEN_DEV}
                - NOWPAYMENTS_API_KEY=${NOWPAYMENTS_API_KEY_DEV}
                - VPN_BASE_URL=${VPN_BASE_URL}
                - VPN_USERNAME=${VPN_USERNAME}
                - VPN_PASSWORD=${VPN_PASSWORD}
        expose:
            - "8000"
        ports:
            - "5555:5555"
        container_name: vpn-python
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        links:
            - db

    #MySQL Service
    db:
        image: mysql:8
        container_name: vpn-mysql
        restart: always
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: vpn_project
            MYSQL_DATABASE: vpn_project
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf


#Volumes
volumes:
    dbdata:
        driver: local
