# docker-compose.dev.yml
version: '3.8'

services:
    webserver:
        image: nginx:alpine
        container_name: vpn-nginx-dev
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app_dev.conf:/etc/nginx/conf.d/app.conf
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        container_name: vpn-python-dev
        env_file:
            - .env.dev
        expose:
            - "8000"
        ports:
            - "5555:5555"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        command: ["uvicorn", "backend.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

    db:
        image: mysql:8
        container_name: vpn-mysql-dev
        restart: always
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: vpn_project
            MYSQL_DATABASE: vpn_project
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
    dbdata:
        driver: local