# docker-compose.prod.yml
version: '3.8'

services:
    webserver:
        image: nginx:alpine
        container_name: vpn-nginx-prod
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/app_prod.conf:/etc/nginx/conf.d/app.conf
            - ./docker/nginx/ssl:/etc/ssl
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: docker/backend/Dockerfile
        container_name: vpn-python-prod
        env_file:
            - .env.prod
        expose:
            - "8000"
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - db
        command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]

    db:
        image: mysql:8
        container_name: vpn-mysql-prod
        restart: always
        tty: true
        ports:
            - "33061:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
    dbdata:
        driver: local